name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - 
              name: Checkout
              uses: actions/checkout@v4
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
              name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.21
            - 
              name: Get dependencies
              run: go mod download
            - 
              name: Build
              run: go build -v ./...

            -
                name: Build locally
                uses: docker/build-push-action@v5
                with:
                    file: Dockerfile
                    push: false
                    tags: user/app:latest

            
